# Generated by Django 4.2.20 on 2025-04-24 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doll',
            name='tags',
            field=models.ManyToManyField(through='core.DollTag', to='core.tag'),
        ),
        migrations.AlterField(
            model_name='dolltag',
            name='tag',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='core.tag'),
        ),
    ]
