# Generated by Django 4.2.20 on 2025-04-19 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_tag_doll'),
    ]

    operations = [
        migrations.CreateModel(
            name='DollTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.doll')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tag')),
            ],
            options={
                'unique_together': {('doll', 'tag')},
            },
        ),
        migrations.AddField(
            model_name='doll',
            name='tags',
            field=models.ManyToManyField(related_name='dolls', through='core.DollTag', to='core.tag'),
        ),
    ]
