# Generated by Django 4.2.20 on 2025-05-07 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_postseen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorite',
            old_name='favorite_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='likes',
            old_name='like_at',
            new_name='created_at',
        ),
    ]
