# Generated by Django 4.2.20 on 2025-06-23 06:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reaction',
            name='doll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.doll'),
        ),
        migrations.AddField(
            model_name='reaction',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='chat.message'),
        ),
        migrations.AddField(
            model_name='message',
            name='custom_emoji',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chat.customemoji'),
        ),
        migrations.AddField(
            model_name='message',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chat.message'),
        ),
        migrations.AddField(
            model_name='message',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.chatroom'),
        ),
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.doll'),
        ),
        migrations.AddField(
            model_name='message',
            name='sticker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chat.sticker'),
        ),
        migrations.AddField(
            model_name='customemoji',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_emojis', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='doll1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chatrooms_as_doll1', to='core.doll'),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='doll2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chatrooms_as_doll2', to='core.doll'),
        ),
        migrations.AlterUniqueTogether(
            name='reaction',
            unique_together={('message', 'doll', 'emoji_code')},
        ),
        migrations.AlterUniqueTogether(
            name='customemoji',
            unique_together={('name', 'owner')},
        ),
        migrations.AlterUniqueTogether(
            name='chatroom',
            unique_together={('doll1', 'doll2')},
        ),
    ]
