# Generated by Django 4.2.20 on 2025-08-19 12:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='customemoji',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='customemoji',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_emojis', to='chat.chatroom'),
        ),
        migrations.AlterUniqueTogether(
            name='customemoji',
            unique_together={('name', 'owner', 'room')},
        ),
    ]
